node {

    checkout scm

    sh "git rev-parse --short HEAD > commit-id"
    tatg = readFile('commit-id').replace("\n","").replace("\r","")

    env.DOCKER_API_VERSION="1.23" 
    appName = "hello-kenzan"
    registryHost = "127.0.0.1:30912/"
    imageName = "${registryHost}${appName}:${tag}"
   
    env.BUILDIMG=imageName


    stage "Build"
    
        sh "docker build -t ${imageName} application/hello-kenzan"
    
    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"

        sh "sed 's#__IMAGE__#'$BUILDIMG'#' application/hello-kenzan/k8s/deployment.yaml | kubectl apply -f -"

}
